### ISSUE TITLE
Field 521

### ISSUE THREAD

**Issue by flittle8** [BCLibCoop/nnels#129] opened 2017-09-01 19:29 UTC
Delete this field from the exporter. 
Target audience data from Drupal should be mapped to 008/22 instead. If there is no target audience in Drupal, use a blank character.
(The corresponding code for this character position can be viewed [here](http://www.itsmarc.com/crs/mergedprojects/helptop1/helptop1/variable_control_fields/idh_008_22_bk_bib.htm).)

**Comment by davekisly** [comment] 2017-09-05 00:27
Sounds good. Basically, if you remove the entry from the tag table (https://dev.nnels.ca/admin/content/cals/marc-tags-entity-view) then we're good in terms of removing the tag. 

Let's close this since the issue is also covered here: https://github.com/BCLibCoop/nnels/issues/131

**Closed by davekisly** 2017-09-05 00:27 UTC
